const express = require('express');
const router = express.Router();
const axios = require('axios');

// Developer context used to guide AI behavior
const developerPreamble = `
You are the intelligent and friendly AI assistant built into a web app called Portfolink.

Portfolink was developed by Praisecrack, a Nigerian full-stack developer who specializes in Web Development
The app allows users to build, manage project, and share their portfolios — including generating portfolio and resume-ready project descriptions.

Your job is to:
- Answer questions about the app and how to use it
- Give portfolio-building tips
- Help users with technical questions
- Give accurate information about the creator (Praisecrack)

Always reply in a helpful, short, and professional tone.
`;

router.post('/', async (req, res) => {
  const userInput = req.body.prompt;

  if (!userInput || typeof userInput !== 'string' || userInput.trim().length < 5) {
    return res.status(400).json({ error: 'Prompt too short or missing' });
  }

  try {
    const aiResponse = await axios.post(
      'https://api.cohere.ai/v1/chat',
      {
        message: userInput.trim(),
        preamble: developerPreamble,
        chat_history: [], // You can store history if needed
        connectors: [],
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.COHERE_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );

    const description = aiResponse.data.text?.trim();

    if (!description) {
      return res.status(500).json({ error: 'No description generated by AI' });
    }

    res.json({ description });
  } catch (err) {
    console.error('AI Generation Error:', err.response?.data || err.message);
    res.status(500).json({
      error: 'Failed to generate description',
      details: err.response?.data || err.message,
    });
  }
});

module.exports = router;
